// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef EVENT_LCIO_H
#define EVENT_LCIO_H 1
#include <string>
namespace EVENT {


#define LCIO_MAJOR_VERSION 1
#define LCIO_MINOR_VERSION 12
#define LCIO_PATCH_LEVEL 2

#define LCIO_VERSION_GE( MAJV , MINV )  ( (  LCIO_MAJOR_VERSION  > MAJV ) || ( (LCIO_MAJOR_VERSION==MAJV) && ( LCIO_MINOR_VERSION >= MINV ) ) )

#define LCIO_PATCHVERSION_GE( MAJV , MINV , PLEV)  ( (  LCIO_MAJOR_VERSION  > MAJV ) ||   ( (LCIO_MAJOR_VERSION==MAJV) && ( LCIO_MINOR_VERSION > MINV ) ) ||   ( (LCIO_MAJOR_VERSION==MAJV) && ( LCIO_MINOR_VERSION == MINV ) && ( LCIO_PATCH_LEVEL >= PLEV ) ) )

/** Global constants used in LCIO.
 *
 * @author gaede
 * @version $Id: LCIO.aid,v 1.71 2010/02/03 14:59:48 engels Exp $
 * @see LCObject
 * @see LCIO
 */

class LCIO {

public: 
    /// Destructor.
    virtual ~LCIO() { /* nop */; }

    // it seems to be impossible to have one declaration for
    // static constants in Java and C++ - so we need to define
    // the same constants twice !!

  public:
    // current version number of lcio
    static const int MAJORVERSION  = LCIO_MAJOR_VERSION ;
    static const int MINORVERSION  = LCIO_MINOR_VERSION ;

    // bits in flag words
    // SimCalorimeterHit (CH)
    static const int CHBIT_LONG   = 31; // long(1) - short(0), (position)
    static const int CHBIT_BARREL = 30 ;  // barrel(1) - endcap(0)
    static const int CHBIT_ID1    = 29 ;  // cellid1 stored
    static const int CHBIT_PDG    = 28 ;   // PDG(1) - no PDG(0) (detailed shower contributions)

    // (raw) calorimeter hit
    static const int RCHBIT_LONG   = 31 ;  // long(1) - short(0) , incl./excl. position
    static const int RCHBIT_BARREL = 30 ;  // barrel(1) - endcap(0)
    static const int RCHBIT_ID1    = 29 ;  // cellid1 stored
    static const int RCHBIT_NO_PTR = 28 ; // 1: pointer tag not added
    static const int RCHBIT_TIME   = 27 ; // 1: time information stored
    static const int RCHBIT_ENERGY_ERROR  = 26 ;   // 1: store energy error

    // raw tracker data (pulses)
    static const int TRAWBIT_ID1   = 31 ;  //  cellid1 stored

    // SimTrackerHit
    static const int THBIT_BARREL = 31 ; // barrel(1) - endcap(0)
    static const int THBIT_MOMENTUM = 30 ; // momentum of particle stored(1) - not stored(0)

    // Tracks
    static const int TRBIT_HITS = 31 ; // hits stored(1) - not stored(0)

    // Cluster
    static const int CLBIT_HITS = 31 ; // hits stored(1) - not stored(0)

    // TPCHit
    static const int TPCBIT_RAW = 31 ; // raw data stored(1) - not stored(0)
    static const int TPCBIT_NO_PTR = 30 ; // 1: pointer tag not added (needed for TrackerHit)


    // LCRelation
    //    static const int LCREL_ONE2MANY = 31 ; // relation is one to many
    static const int LCREL_WEIGHTED = 31 ; // relations has weights


    // LCGenericObject
    static const int GOBIT_FIXED = 31 ; // is fixed size

    static const int READ_ONLY =  0 ;
    static const int UPDATE   =  1 ;
    // error handling
    static const int ERROR   =  0 ;
    static const int SUCCESS =  1 ;

    //write modes
    static const int WRITE_NEW = 0 ;
    static const int WRITE_APPEND = 1 ;

    // type names:
    static const std::string LCEVENT ;
    static const std::string LCRUNHEADER ;
    static const std::string LCCOLLECTION ;
    static const char*  MCPARTICLE ;
    static const std::string SIMCALORIMETERHIT ;
    static const std::string RAWCALORIMETERHIT ;
    static const std::string CALORIMETERHIT ;
    static const std::string SIMTRACKERHIT ;
    static const std::string TPCHIT ;
    static const std::string TRACKERRAWDATA ;
    static const std::string TRACKERDATA ;
    static const std::string TRACKERPULSE ;
    static const std::string TRACKERHIT ;
    static const std::string LCSTRVEC ;
    static const std::string LCFLOATVEC ;
    static const std::string LCINTVEC ;
    static const std::string TRACK ;
    static const std::string CLUSTER ;
    static const std::string RECONSTRUCTEDPARTICLE ;
    static const std::string LCRELATION ;
    static const std::string LCGENERICOBJECT ;
    static const std::string PARTICLEID;
    static const std::string VERTEX;

    // reserved names, e.g. name of event/collections paramaters

    static const std::string CellIDEncoding ;
}; // class
} // namespace EVENT
#endif /* ifndef EVENT_LCIO_H */
